[package]
name = "rust-algorithms"
version = "0.1.0"
authors = ["benjamin <benjamin.zanger@tum.de>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
crossbeam = "0.7"


[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "sort"
harness = false
